# ~/.config/starship.toml

format = '''
$directory$git_branch$git_status$character
'''

right_format = '$cmd_duration'
add_newline = true
palette = 'term'

[directory]
style = 'blue'
truncate_to_repo = false
truncation_length = 3
truncation_symbol = '.../'

[git_branch]
format = '[$branch](green)'

[git_status]
format = '[$all_status$ahead_behind(lightblue) ](green)'
untracked = '?'
modified = '!'
staged = '*'
deleted = '-'

[palettes.term]
brightgreen = '#5fd787'
lightblue = '#5fafff'
orange = '#ffaf01'
grey = '#787878'

[cmd_duration]
min_time = 500
format = '[$duration](grey)'
